'use client'

import Image from 'next/image'
import {
  useCallback,
  useEffect,
  useRef,
  useState,
  type CSSProperties,
} from 'react'

import { useLocale, useTranslations } from 'next-intl'

import {
  HOME_V4_ENGINE,
  HOME_V4_FN_AUDIO,
  HOME_V4_FN_AUDIO_LINES,
  HOME_V4_GLYPHS,
} from '@/constants/homepage-v4'
import type { AppLocale } from '@/i18n/routing'

import { HomeV4FnFrame } from './HomeV4FnFrame'

interface HomeV4FnAudioProps {
  /** True while this is the page on screen. Drives play / reset. */
  active: boolean
  eyebrow: string
  title: string
}

/** How many bubbles have landed, and how many have played their waveform. */
interface AudioBeats {
  arrived: number
  played: number
}

const AT_REST: AudioBeats = { arrived: 0, played: 0 }

/**
 * The transport. Exactly one line can hold it, which is what makes starting a
 * second note stop the first — there is nowhere for two to be.
 */
interface AudioTransport {
  /** The line that owns the transport, or null when the room is silent. */
  id: string | null
  /** Whether it is sounding right now (false = paused mid-clip). */
  sounding: boolean
  /** 0…1 of the clip already heard. Sweeps the waveform. */
  progress: number
  /** Seconds already heard, for the counter. */
  elapsed: number
}

const SILENT: AudioTransport = {
  id: null,
  sounding: false,
  progress: 0,
  elapsed: 0,
}

/** `0:07` — the same shape as the resting label the message files carry. */
function formatElapsed(seconds: number): string {
  const whole = Math.floor(seconds)
  return `${Math.floor(whole / 60)}:${String(whole % 60).padStart(2, '0')}`
}

/**
 * 功能页 03 · 声音 — the dubbing room.
 *
 * Three lines arrive as chat messages, each with a voice note whose bars grow a
 * beat after the bubble settles (the growth is a per-bar CSS delay off `--i`,
 * so the waveform draws itself left to right for free). Two library voices and
 * one cloned voice, which is the page's whole argument.
 *
 * ⚠ Those two motions are different things and must not be merged: the bars
 * *growing* is "the message arrived", the bars *changing colour* is "this much
 * of it has been heard". The first is choreography off `beats`; the second is
 * `--progress`, written from `timeupdate` — real playback position, never a
 * CSS animation pretending to be one.
 *
 * The three faces are this product's own pictures too — one cel-shaded portrait
 * per speaker off GPT Image 2 — and the picker in the input row shows the same
 * three files, so 「谁在说」reads the same in the thread and in the controls.
 *
 * The notes really play. Nine clips (3 lines × 3 locales), all generated by
 * this product through `/api/generate-audio` on Fish Audio S2.1, and all
 * `preload="none"`: an unclicked page downloads zero audio bytes. Nothing plays
 * on its own — a visitor gets sound only by asking for it, and leaving the page
 * cuts it immediately.
 *
 * A chat column is already the mobile shape, so this page only trims type
 * sizes below 768px rather than re-laying anything out.
 */
export function HomeV4FnAudio({ active, eyebrow, title }: HomeV4FnAudioProps) {
  const t = useTranslations('Homepage')
  const locale = useLocale() as AppLocale
  const [beats, setBeats] = useState<AudioBeats>(AT_REST)
  const [transport, setTransport] = useState<AudioTransport>(SILENT)

  /* One <audio> per line, registered by the element's own ref callback. */
  const clips = useRef(new Map<string, HTMLAudioElement>())

  /** Stop every element and put it back at zero. Touches no React state. */
  const rewindClips = useCallback(() => {
    clips.current.forEach((clip) => {
      clip.pause()
      clip.currentTime = 0
    })
  }, [])

  const silence = useCallback(() => {
    rewindClips()
    setTransport(SILENT)
  }, [rewindClips])

  /**
   * Leaving has to silence the room in the render it happens, not one frame
   * later — this is React's "adjust state when a prop changes", deliberately
   * not an effect. An effect would paint one frame with the pill still lit,
   * and the state would land after the deck had already begun the slide.
   */
  const [activeLastRender, setActiveLastRender] = useState(active)
  if (activeLastRender !== active) {
    setActiveLastRender(active)
    if (!active) setTransport(SILENT)
  }

  const toggle = useCallback(
    (id: string) => {
      const clip = clips.current.get(id)
      if (!clip) return

      if (transport.id === id && transport.sounding) {
        clip.pause()
        setTransport((current) => ({ ...current, sounding: false }))
        return
      }

      /* Handing the transport over: whoever had it goes back to the start. */
      clips.current.forEach((other, otherId) => {
        if (otherId === id) return
        other.pause()
        other.currentTime = 0
      })

      /* A play() can still be refused (a data-saver profile, a paused-media
         setting). Say nothing and stay at rest rather than lighting a playing
         state over silence. */
      void clip
        .play()
        .then(() =>
          setTransport({
            id,
            sounding: true,
            progress: 0,
            elapsed: clip.currentTime,
          }),
        )
        .catch(() => setTransport(SILENT))
    },
    [transport.id, transport.sounding],
  )

  const onTimeUpdate = useCallback((id: string) => {
    const clip = clips.current.get(id)
    if (!clip) return
    const total = clip.duration
    setTransport((current) =>
      current.id === id
        ? {
            ...current,
            progress: total > 0 ? clip.currentTime / total : 0,
            elapsed: clip.currentTime,
          }
        : current,
    )
  }, [])

  useEffect(() => {
    if (!active) {
      /* Sound stops the moment the page starts leaving — unlike the video page,
         a voice carrying over the slide would be heard on top of the next one.
         (The transport state was already cleared above, in render; this is the
         other half, the elements themselves.) The bubbles still rewind on the
         page's own clock. */
      rewindClips()
      const rewind = window.setTimeout(
        () => setBeats(AT_REST),
        HOME_V4_ENGINE.PAGE_MS,
      )
      return () => window.clearTimeout(rewind)
    }

    const timers: number[] = []
    const at = (fn: () => void, ms: number) => {
      timers.push(window.setTimeout(fn, HOME_V4_FN_AUDIO.ENTER_DELAY_MS + ms))
    }

    HOME_V4_FN_AUDIO_LINES.forEach((_, index) => {
      const landsAt =
        HOME_V4_FN_AUDIO.MSG_START_MS + index * HOME_V4_FN_AUDIO.MSG_STEP_MS
      at(
        () => setBeats((current) => ({ ...current, arrived: index + 1 })),
        landsAt,
      )
      at(
        () => setBeats((current) => ({ ...current, played: index + 1 })),
        landsAt + HOME_V4_FN_AUDIO.PLAY_DELAY_MS,
      )
    })

    return () => timers.forEach((id) => window.clearTimeout(id))
  }, [active, rewindClips])

  return (
    <HomeV4FnFrame eyebrow={eyebrow} title={title}>
      <div className="fn-audio">
        <div className="bar">
          <span className="t">{t('v4.fn.audio.room')}</span>
          <span className="p">{t('v4.fn.audio.meta')}</span>
        </div>

        <div className="flow">
          {HOME_V4_FN_AUDIO_LINES.map((line, index) => {
            const classes = [
              'msg',
              line.mine ? 'me' : '',
              index < beats.arrived ? 'in' : '',
              index < beats.played ? 'played' : '',
            ]
              .filter(Boolean)
              .join(' ')

            const holdsTransport = transport.id === line.id
            const sounding = holdsTransport && transport.sounding

            return (
              <div className={classes} key={line.id}>
                {/* The face is the speaker; the one glyph the message files
                    carry is that speaker's name, so it is the `alt`. */}
                <span className="ava">
                  <Image
                    src={line.avatar}
                    alt={t(`v4.fn.audio.lines.${line.id}.avatar`)}
                    width={HOME_V4_FN_AUDIO.AVATAR_PX}
                    height={HOME_V4_FN_AUDIO.AVATAR_PX}
                  />
                </span>
                <span className="grp">
                  <span className="who">
                    {t(`v4.fn.audio.lines.${line.id}.who`)}
                  </span>
                  <span className="bub">
                    {t(`v4.fn.audio.lines.${line.id}.text`)}
                  </span>
                  <span
                    className={[
                      'voice',
                      holdsTransport ? 'live' : '',
                      sounding ? 'sounding' : '',
                    ]
                      .filter(Boolean)
                      .join(' ')}
                    style={
                      {
                        '--progress': holdsTransport ? transport.progress : 0,
                      } as CSSProperties
                    }
                  >
                    <button
                      type="button"
                      className="play"
                      aria-label={t(
                        sounding
                          ? `v4.fn.audio.lines.${line.id}.pauseLabel`
                          : `v4.fn.audio.lines.${line.id}.playLabel`,
                      )}
                      onClick={() => toggle(line.id)}
                    >
                      {sounding ? HOME_V4_GLYPHS.pause : HOME_V4_GLYPHS.play}
                    </button>
                    <span
                      className="wv"
                      style={{ '--n': line.wave.length } as CSSProperties}
                    >
                      {line.wave.map((height, bar) => (
                        <i
                          key={bar}
                          style={{ '--i': bar, '--h': height } as CSSProperties}
                        />
                      ))}
                    </span>
                    <span className="dur">
                      {holdsTransport
                        ? formatElapsed(transport.elapsed)
                        : t(`v4.fn.audio.lines.${line.id}.duration`)}
                    </span>
                    {/* preload="none": an unclicked page fetches no audio. */}
                    <audio
                      ref={(element) => {
                        if (element) clips.current.set(line.id, element)
                        else clips.current.delete(line.id)
                      }}
                      preload="none"
                      src={line.clips[locale]}
                      onTimeUpdate={() => onTimeUpdate(line.id)}
                      onEnded={silence}
                    />
                  </span>
                </span>
              </div>
            )
          })}
        </div>

        <div className="inrow">
          <span className="picks">
            {/* Same three faces as the messages above — that repetition is the
                whole point of the row: 「这条是谁说的」and「我在给谁配音」
                have to be the same picture. */}
            {HOME_V4_FN_AUDIO_LINES.map((line, index) => (
              <span className={`pick${index === 0 ? ' on' : ''}`} key={line.id}>
                <Image
                  src={line.avatar}
                  alt={t(`v4.fn.audio.lines.${line.id}.avatar`)}
                  width={HOME_V4_FN_AUDIO.PICK_PX}
                  height={HOME_V4_FN_AUDIO.PICK_PX}
                />
              </span>
            ))}
            <span className="pick add" title={t('v4.fn.audio.addVoice')}>
              {HOME_V4_GLYPHS.plus}
            </span>
          </span>
          <span className="tx">{t('v4.fn.audio.placeholder')}</span>
          <span className="cur2" />
          {/* A picture of the button, not a control — nothing to submit. */}
          <button type="button" className="go">
            {t('v4.fn.audio.generate')}
          </button>
        </div>
      </div>
    </HomeV4FnFrame>
  )
}
