import {
  AI_ADAPTER_TYPES,
  getDefaultProviderConfig,
} from '@/constants/providers'
import { FEATURE_FLAGS } from '@/constants/feature-flags'
import { AI_MODELS } from '@/constants/models/enum'
import type { ModelOption } from '@/constants/models/types'
import { getRunnerCheckpointById } from '@/constants/runner-checkpoints'

/** Cold starts (scale-to-zero) can run 150s+ — give runner models a long ceiling. */
const RUNNER_TIMEOUT_MS = 600_000

/**
 * Image generation models, ordered by product recommendation. The catalog is
 * intentionally lean: one flagship plus specialized models with distinct roles.
 */
export const IMAGE_MODEL_OPTIONS: ModelOption[] = [
  {
    id: AI_MODELS.OPENAI_GPT_IMAGE_2,
    cost: 3,
    adapterType: AI_ADAPTER_TYPES.OPENAI,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.OPENAI),
    externalModelId: AI_MODELS.OPENAI_GPT_IMAGE_2,
    outputType: 'IMAGE',
    available: true,
    officialUrl: 'https://developers.openai.com/api/docs/models/gpt-image-2',
    qualityTier: 'premium',
    styleTag: 'general',
    maxPromptChars: 32_000,
  },
  {
    id: AI_MODELS.GEMINI_PRO_IMAGE,
    cost: 3,
    adapterType: AI_ADAPTER_TYPES.GEMINI,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.GEMINI),
    externalModelId: 'gemini-3-pro-image-preview',
    outputType: 'IMAGE',
    available: true,
    officialUrl: 'https://ai.google.dev/gemini-api/docs/image-generation',
    qualityTier: 'premium',
    styleTag: 'general',
    maxPromptChars: 8000,
  },
  {
    id: AI_MODELS.FLUX_2_PRO,
    cost: 2,
    adapterType: AI_ADAPTER_TYPES.FAL,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.FAL),
    externalModelId: 'fal-ai/flux-2-pro',
    outputType: 'IMAGE',
    available: true,
    officialUrl: 'https://fal.ai/models/fal-ai/flux-2-pro',
    qualityTier: 'premium',
    styleTag: 'photorealistic',
    maxPromptChars: 8000,
  },
  {
    id: AI_MODELS.SEEDREAM_45,
    cost: 2,
    adapterType: AI_ADAPTER_TYPES.FAL,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.FAL),
    externalModelId: 'fal-ai/bytedance/seedream/v4.5/text-to-image',
    outputType: 'IMAGE',
    available: true,
    officialUrl: 'https://seed.bytedance.com/en/seedream4_5',
    qualityTier: 'premium',
    styleTag: 'artistic',
  },
  {
    // VolcEngine (火山方舟) direct-API variant of Seedream 4.5 — cn region.
    // Additive alongside the fal.ai entry above. Adapter passes externalModelId
    // through as the Ark `model` field.
    id: AI_MODELS.SEEDREAM_45_VOLCENGINE,
    cost: 2,
    adapterType: AI_ADAPTER_TYPES.VOLCENGINE,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.VOLCENGINE),
    externalModelId: 'doubao-seedream-4-5-251128',
    outputType: 'IMAGE',
    available: true,
    officialUrl:
      'https://console.volcengine.com/ark/region:ark+cn-beijing/model',
    qualityTier: 'premium',
    styleTag: 'artistic',
  },
  {
    id: AI_MODELS.IDEOGRAM_3,
    cost: 2,
    adapterType: AI_ADAPTER_TYPES.FAL,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.FAL),
    externalModelId: 'ideogram/v4',
    outputType: 'IMAGE',
    available: true,
    officialUrl: 'https://fal.ai/models/ideogram/v4',
    qualityTier: 'premium',
    styleTag: 'design',
    maxPromptChars: 1000,
  },
  {
    id: AI_MODELS.RECRAFT_V4_PRO,
    cost: 2,
    adapterType: AI_ADAPTER_TYPES.FAL,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.FAL),
    externalModelId: 'fal-ai/recraft/v4/pro/text-to-image',
    outputType: 'IMAGE',
    available: true,
    officialUrl: 'https://www.recraft.ai/docs/api-reference/getting-started',
    qualityTier: 'premium',
    styleTag: 'design',
    maxPromptChars: 10_000,
  },
  {
    id: AI_MODELS.NOVELAI_V45_FULL,
    cost: 2,
    adapterType: AI_ADAPTER_TYPES.NOVELAI,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.NOVELAI),
    externalModelId: 'nai-diffusion-4-5-full',
    outputType: 'IMAGE',
    available: true,
    officialUrl: 'https://docs.novelai.net/en/image/models',
    qualityTier: 'premium',
    styleTag: 'anime',
  },
  {
    id: AI_MODELS.NOVELAI_V45_CURATED,
    cost: 2,
    adapterType: AI_ADAPTER_TYPES.NOVELAI,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.NOVELAI),
    externalModelId: 'nai-diffusion-4-5-curated',
    outputType: 'IMAGE',
    available: true,
    officialUrl: 'https://docs.novelai.net/en/image/models',
    qualityTier: 'premium',
    styleTag: 'anime',
  },
  {
    id: AI_MODELS.ILLUSTRIOUS_XL,
    cost: 2,
    adapterType: AI_ADAPTER_TYPES.REPLICATE,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.REPLICATE),
    externalModelId: 'delta-lock/noobai-xl',
    outputType: 'IMAGE',
    available: true,
    officialUrl: 'https://replicate.com/delta-lock/noobai-xl',
    qualityTier: 'standard',
    styleTag: 'anime',
    supportsLora: true,
  },
  {
    id: AI_MODELS.FLUX_LORA,
    cost: 1,
    adapterType: AI_ADAPTER_TYPES.FAL,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.FAL),
    externalModelId: 'fal-ai/flux-lora',
    outputType: 'IMAGE',
    available: true,
    officialUrl: 'https://fal.ai/models/fal-ai/flux-lora',
    qualityTier: 'standard',
    styleTag: 'general',
    supportsLora: true,
  },
  {
    id: AI_MODELS.FLUX_2_FLASH,
    cost: 1,
    adapterType: AI_ADAPTER_TYPES.FAL,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.FAL),
    externalModelId: 'fal-ai/flux-2/flash',
    outputType: 'IMAGE',
    available: true,
    officialUrl: 'https://fal.ai/models/fal-ai/flux-2/flash',
    qualityTier: 'budget',
    styleTag: 'general',
    maxPromptChars: 8000,
  },
  {
    id: AI_MODELS.GEMINI_FLASH_IMAGE,
    cost: 2,
    adapterType: AI_ADAPTER_TYPES.GEMINI,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.GEMINI),
    externalModelId: 'gemini-3.1-flash-image',
    outputType: 'IMAGE',
    available: true,
    freeTier: true,
    officialUrl:
      'https://ai.google.dev/gemini-api/docs/models/gemini-3.1-flash-image',
    qualityTier: 'standard',
    styleTag: 'general',
    maxPromptChars: 8000,
  },
  {
    id: AI_MODELS.FLUX_KONTEXT_MAX,
    cost: 3,
    adapterType: AI_ADAPTER_TYPES.FAL,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.FAL),
    externalModelId: 'fal-ai/flux-pro/kontext/max/multi',
    outputType: 'IMAGE',
    available: true,
    officialUrl: 'https://fal.ai/models/fal-ai/flux-pro/kontext/max/multi',
    timeoutMs: 300_000,
    qualityTier: 'premium',
    styleTag: 'general',
    supportsLora: true,
  },
  {
    id: AI_MODELS.ANIMA_PENCIL_XL,
    cost: 2,
    adapterType: AI_ADAPTER_TYPES.REPLICATE,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.REPLICATE),
    externalModelId: 'lucataco/animapencil-xl-v4',
    outputType: 'IMAGE',
    available: false,
    officialUrl: 'https://replicate.com/explore?query=anima',
    qualityTier: 'standard',
    styleTag: 'anime',
    supportsLora: true,
  },
  // ─── Comfy Runner (RunPod Serverless ComfyUI) ──────────────────────
  // Faithful Civitai-recipe clones for checkpoints hosted providers can't
  // run (community LoRA layer formats, dead/nonexistent hosted endpoints).
  // Gated behind FEATURE_FLAGS.comfyRunner — owner-only single endpoint with
  // a hard monthly budget cap (RUNNER_MONTHLY_LIMIT). See
  // docs/plans/comfy-runner-HANDOFF-2026-07.md §4.2b/§8.
  {
    id: AI_MODELS.ILLUSTRIOUS_RECIPE_CLONE,
    cost: 3,
    adapterType: AI_ADAPTER_TYPES.RUNNER,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.RUNNER),
    externalModelId: getRunnerCheckpointById('waiIllustriousSDXL_v150')!.id,
    outputType: 'IMAGE',
    available: FEATURE_FLAGS.comfyRunner,
    qualityTier: 'standard',
    styleTag: 'anime',
    supportsLora: true,
    timeoutMs: RUNNER_TIMEOUT_MS,
  },
  {
    id: AI_MODELS.ANIMA_PENCIL_XL_RUNNER,
    cost: 3,
    adapterType: AI_ADAPTER_TYPES.RUNNER,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.RUNNER),
    externalModelId: getRunnerCheckpointById('animaPencilXL_v500')!.id,
    outputType: 'IMAGE',
    available: FEATURE_FLAGS.comfyRunner,
    qualityTier: 'standard',
    styleTag: 'anime',
    supportsLora: true,
    timeoutMs: RUNNER_TIMEOUT_MS,
  },
  {
    id: AI_MODELS.PONY_DIFFUSION_V6,
    cost: 3,
    adapterType: AI_ADAPTER_TYPES.RUNNER,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.RUNNER),
    externalModelId: getRunnerCheckpointById('ponyDiffusionV6XL')!.id,
    outputType: 'IMAGE',
    available: FEATURE_FLAGS.comfyRunner,
    qualityTier: 'standard',
    styleTag: 'anime',
    supportsLora: true,
    timeoutMs: RUNNER_TIMEOUT_MS,
  },
  {
    id: AI_MODELS.SDXL_10_RUNNER,
    cost: 3,
    adapterType: AI_ADAPTER_TYPES.RUNNER,
    providerConfig: getDefaultProviderConfig(AI_ADAPTER_TYPES.RUNNER),
    externalModelId: getRunnerCheckpointById('sdXL_v10VAEFix')!.id,
    outputType: 'IMAGE',
    available: FEATURE_FLAGS.comfyRunner,
    qualityTier: 'standard',
    styleTag: 'general',
    supportsLora: true,
    timeoutMs: RUNNER_TIMEOUT_MS,
  },
]
