import type { PromptTagDefinition } from '@/types/prompt-tags'

export const PROMPT_TAG_CURATED_DEFINITIONS = [
  {
    id: 'system:quality:masterpiece',
    type: 'quality',
    source: 'system',
    label: 'Masterpiece',
    promptText: 'masterpiece',
    aliases: ['best quality', 'high quality', '高质量', '精致', '高品質'],
    category: 'quality',
    polarity: 'positive',
    modelFamilies: ['any'],
    orderGroup: 10,
  },
  {
    id: 'system:quality:high-detail',
    type: 'quality',
    source: 'system',
    label: 'High detail',
    promptText: 'highly detailed',
    aliases: ['detailed', 'fine detail', '细节', '高细节', 'ディテール'],
    category: 'quality',
    polarity: 'positive',
    modelFamilies: ['any'],
    orderGroup: 10,
  },
  {
    id: 'system:aesthetic:cinematic',
    type: 'aesthetic',
    source: 'system',
    label: 'Cinematic',
    promptText: 'cinematic composition',
    aliases: ['film still', 'movie frame', '电影感', '电影', 'シネマ'],
    category: 'style',
    polarity: 'positive',
    modelFamilies: ['any'],
    orderGroup: 30,
  },
  {
    id: 'system:style:anime',
    type: 'style',
    source: 'system',
    label: 'Anime',
    promptText: 'anime style',
    aliases: ['illustration', '2d anime', '动漫', '二次元', 'アニメ'],
    category: 'style',
    polarity: 'positive',
    modelFamilies: ['sdxl', 'anima', 'novelai', 'any'],
    orderGroup: 30,
  },
  {
    id: 'system:style:photoreal',
    type: 'style',
    source: 'system',
    label: 'Photoreal',
    promptText: 'photorealistic',
    aliases: ['photo realistic', 'realistic', '写实', '真实', 'リアル'],
    category: 'style',
    polarity: 'positive',
    modelFamilies: ['flux', 'sdxl', 'any'],
    orderGroup: 30,
  },
  {
    id: 'system:lighting:soft',
    type: 'lighting',
    source: 'system',
    label: 'Soft light',
    promptText: 'soft lighting',
    aliases: [
      'diffused light',
      'gentle lighting',
      '柔光',
      '柔和光线',
      '柔らかい光',
    ],
    category: 'lighting',
    polarity: 'positive',
    modelFamilies: ['any'],
    orderGroup: 50,
  },
  {
    id: 'system:lighting:rim',
    type: 'lighting',
    source: 'system',
    label: 'Rim light',
    promptText: 'rim lighting',
    aliases: ['back light', 'edge light', '轮廓光', '逆光', 'リムライト'],
    category: 'lighting',
    polarity: 'positive',
    modelFamilies: ['any'],
    orderGroup: 50,
  },
  {
    id: 'system:camera:close-up',
    type: 'camera',
    source: 'system',
    label: 'Close-up',
    promptText: 'close-up shot',
    aliases: ['portrait crop', 'tight shot', '特写', '近景', 'クローズアップ'],
    category: 'camera',
    polarity: 'positive',
    modelFamilies: ['any'],
    orderGroup: 60,
  },
  {
    id: 'system:camera:wide-shot',
    type: 'camera',
    source: 'system',
    label: 'Wide shot',
    promptText: 'wide shot',
    aliases: [
      'establishing shot',
      'full scene',
      '远景',
      '全景',
      'ワイドショット',
    ],
    category: 'camera',
    polarity: 'positive',
    modelFamilies: ['any'],
    orderGroup: 60,
  },
  {
    id: 'system:scene:studio-background',
    type: 'scene',
    source: 'system',
    label: 'Studio background',
    promptText: 'clean studio background',
    aliases: [
      'simple backdrop',
      'minimal background',
      '纯色背景',
      '干净背景',
      'シンプル背景',
    ],
    category: 'scene',
    polarity: 'positive',
    modelFamilies: ['any'],
    orderGroup: 70,
  },
  {
    id: 'system:negative:low-quality',
    type: 'negative',
    source: 'system',
    label: 'Low quality',
    promptText: 'low quality',
    aliases: ['bad quality', 'poor quality', '低质量', '劣质', '低品質'],
    category: 'quality',
    polarity: 'negative',
    modelFamilies: ['any'],
    orderGroup: 10,
  },
  {
    id: 'system:negative:blur',
    type: 'negative',
    source: 'system',
    label: 'Blur',
    promptText: 'blurry',
    aliases: ['blurred', 'out of focus', '模糊', '失焦', 'ぼけ'],
    category: 'quality',
    polarity: 'negative',
    modelFamilies: ['any'],
    orderGroup: 20,
  },
  {
    id: 'system:negative:bad-hands',
    type: 'negative',
    source: 'system',
    label: 'Bad hands',
    promptText: 'bad hands',
    aliases: [
      'deformed hands',
      'extra fingers',
      '坏手',
      '手部错误',
      '崩れた手',
    ],
    category: 'anatomy',
    polarity: 'negative',
    modelFamilies: ['any'],
    orderGroup: 30,
  },
  {
    id: 'system:negative:text',
    type: 'negative',
    source: 'system',
    label: 'Text artifacts',
    promptText: 'text, watermark, logo',
    aliases: ['watermark', 'logo', 'signature', '水印', '文字', '透かし'],
    category: 'artifacts',
    polarity: 'negative',
    modelFamilies: ['any'],
    orderGroup: 40,
  },
] satisfies readonly PromptTagDefinition[]
