import type { PromptTagDefinition } from '@/types/prompt-tags'

// Generated by scripts/import-danbooru-prompt-tags.ts.
// Keep the default file tiny so Studio does not bundle a large CSV-derived
// corpus until the import is explicitly run.
export const PROMPT_TAG_DANBOORU_DEFINITIONS =
  [] satisfies readonly PromptTagDefinition[]
