/**
 * Marker stored in Generation.provider (and .model) for assets the user
 * uploaded locally (not generated by an AI provider). Lets the asset
 * browser surface a dedicated "Local assets" section without a schema
 * change, and lets billing / usage code skip these rows.
 */
export const USER_UPLOAD_PROVIDER = 'user-upload'

/**
 * Server-side business cap on a user-upload's raw bytes (15 MB). Enforced in
 * `upload-image.service` (buffer path) and the multipart route's early
 * content-length short-circuit. Matches `CLIENT_UPLOAD_MAX_BYTES` so a file
 * the client is willing to send is a file the server is willing to store.
 */
export const USER_UPLOAD_MAX_BYTES = 15 * 1024 * 1024

/**
 * Client-side cap for local-file uploads. Files at or under this are sent
 * *as-is* (no re-encode, no quality loss) via `multipart/form-data`; only
 * files larger than this get squeezed down to fit — see `compress-image.ts`.
 *
 * Uploads go through `multipart/form-data`, not a base64 data URL in a JSON
 * body, so there is no ~33% base64 inflation to budget for. The platform
 * already streams multipart bodies well past this via the reference-video
 * (50 MB) and reference-audio (25 MB) upload routes, so 15 MB has ample
 * headroom. (The old 3 MB base64 path crushed quality — every good image got
 * re-encoded down; this preserves it.)
 */
export const CLIENT_UPLOAD_MAX_BYTES = 15 * 1024 * 1024

/**
 * Video uploads go directly from the browser to R2 and are preserved as-is.
 * R2 accepts a single PUT up to 5 GiB. Keep this platform limit separate from
 * the client-compressible image path; the completion endpoint only reads the
 * object's metadata and signature bytes, never the full video into memory.
 */
export const USER_VIDEO_UPLOAD_MAX_BYTES = 5 * 1024 * 1024 * 1024
export const CLIENT_VIDEO_UPLOAD_MAX_BYTES = USER_VIDEO_UPLOAD_MAX_BYTES

/**
 * Asset-library audio uploads use the same browser-direct single PUT path as
 * videos. Keep them out of the buffered image path: audio files are preserved
 * byte-for-byte and finalized from R2 metadata + signature bytes only.
 */
export const USER_AUDIO_UPLOAD_MAX_BYTES = 5 * 1024 * 1024 * 1024
export const CLIENT_AUDIO_UPLOAD_MAX_BYTES = USER_AUDIO_UPLOAD_MAX_BYTES

/** Bytes needed to identify the supported video containers safely. */
export const USER_VIDEO_UPLOAD_SIGNATURE_BYTES = 4096

/** Bytes needed to identify all supported audio containers safely. */
export const USER_AUDIO_UPLOAD_SIGNATURE_BYTES = 4096

/**
 * Short-lived presigned PUT URL window for browser-direct R2 uploads. Keep it
 * tight: the client only needs enough time to send one prepared image file.
 */
export const USER_UPLOAD_DIRECT_URL_EXPIRES_SECONDS = 5 * 60

/** Large videos need a wider window than image uploads to finish one PUT. */
export const USER_VIDEO_UPLOAD_DIRECT_URL_EXPIRES_SECONDS = 60 * 60

/** Large audio files use the same one-hour direct-upload window as videos. */
export const USER_AUDIO_UPLOAD_DIRECT_URL_EXPIRES_SECONDS = 60 * 60

/**
 * Accepted image MIME types. Deliberately narrow — `image/svg+xml` is excluded
 * because SVG can carry inline scripts that execute when opened from the CDN.
 *
 * Server-side, the *real* format is re-verified against the buffer via
 * `sharp.metadata()` in `upload-image.service.ts` so a client can't lie
 * about the MIME type in the data URL header.
 */
export const USER_IMAGE_UPLOAD_ACCEPTED_MIME_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/gif',
] as const

export const USER_VIDEO_UPLOAD_ACCEPTED_MIME_TYPES = [
  'video/mp4',
  'video/quicktime',
  'video/x-quicktime',
  'video/webm',
] as const

export const USER_AUDIO_UPLOAD_ACCEPTED_MIME_TYPES = [
  'audio/mpeg',
  'audio/mp3',
  'audio/wav',
  'audio/wave',
  'audio/x-wav',
  'audio/mp4',
  'audio/m4a',
  'audio/x-m4a',
  'audio/flac',
  'audio/x-flac',
  'audio/ogg',
  'audio/webm',
] as const

/** Accepted media for the full asset-library upload entrance. */
export const USER_UPLOAD_ACCEPTED_MIME_TYPES = [
  ...USER_IMAGE_UPLOAD_ACCEPTED_MIME_TYPES,
  ...USER_VIDEO_UPLOAD_ACCEPTED_MIME_TYPES,
  ...USER_AUDIO_UPLOAD_ACCEPTED_MIME_TYPES,
] as const

export type AcceptedImageUploadMimeType =
  (typeof USER_IMAGE_UPLOAD_ACCEPTED_MIME_TYPES)[number]

export type AcceptedVideoUploadMimeType =
  (typeof USER_VIDEO_UPLOAD_ACCEPTED_MIME_TYPES)[number]

export type AcceptedAudioUploadMimeType =
  (typeof USER_AUDIO_UPLOAD_ACCEPTED_MIME_TYPES)[number]

export type AcceptedUploadMimeType =
  (typeof USER_UPLOAD_ACCEPTED_MIME_TYPES)[number]

/**
 * `sharp.metadata().format` values that correspond to the allowed MIME
 * types above. Used by `upload-image.service.ts` for magic-byte validation.
 */
export const USER_UPLOAD_ACCEPTED_SHARP_FORMATS = new Set([
  'jpeg',
  'png',
  'webp',
  'gif',
])
