/**
 * Marker stored in Generation.provider (and .model) for assets the user
 * uploaded locally (not generated by an AI provider). Lets the asset
 * browser surface a dedicated "Local assets" section without a schema
 * change, and lets billing / usage code skip these rows.
 */
export const USER_UPLOAD_PROVIDER = 'user-upload'

/** Maximum size in bytes for a single user-upload (5 MB) */
export const USER_UPLOAD_MAX_BYTES = 5 * 1024 * 1024

/** Accepted MIME types for user uploads (image only) */
export const USER_UPLOAD_ACCEPTED_MIME_PREFIXES = ['image/'] as const
