import { readFile, writeFile } from 'node:fs/promises'
import process from 'node:process'

import type { PromptTagDefinition } from '../src/types/prompt-tags'

const DEFAULT_MIN_POST_COUNT = 5000
const OUTPUT_PATH = 'src/constants/prompt-tags.danbooru.generated.ts'
const INCLUDED_DANBOORU_TYPES = new Set(['0', '5'])
const EXCLUDED_NAME_PATTERNS = [
  /^rating[:_]/i,
  /(^|_)(artist|copyright|character|username)($|_)/i,
  /(^|_)(loli|shota|gore|explicit|penis|vagina|nipples?)($|_)/i,
]

interface ImportOptions {
  inputPath: string
  outputPath: string
  minPostCount: number
}

interface DanbooruCsvRow {
  name: string
  type: string
  postCount: number
  aliases: string[]
}

function parseArgs(argv: readonly string[]): ImportOptions {
  const inputPath = argv[2]
  if (!inputPath) {
    throw new Error(
      'Usage: npx tsx scripts/import-danbooru-prompt-tags.ts <danbooru.csv> [output.ts] [minPostCount]',
    )
  }

  return {
    inputPath,
    outputPath: argv[3] ?? OUTPUT_PATH,
    minPostCount:
      argv[4] !== undefined ? Number(argv[4]) : DEFAULT_MIN_POST_COUNT,
  }
}

function parseCsvLine(line: string): string[] {
  const cells: string[] = []
  let current = ''
  let inQuotes = false

  for (let index = 0; index < line.length; index += 1) {
    const char = line[index]
    const next = line[index + 1]

    if (char === '"' && next === '"') {
      current += '"'
      index += 1
      continue
    }
    if (char === '"') {
      inQuotes = !inQuotes
      continue
    }
    if (char === ',' && !inQuotes) {
      cells.push(current)
      current = ''
      continue
    }
    current += char
  }

  cells.push(current)
  return cells
}

function parseDanbooruRow(line: string): DanbooruCsvRow | null {
  const [name, type, postCountText, aliasesText = ''] = parseCsvLine(line)
  const postCount = Number(postCountText)
  if (!name || !type || !Number.isFinite(postCount)) return null

  return {
    name,
    type,
    postCount,
    aliases: aliasesText
      .split(',')
      .map((alias) => alias.trim())
      .filter(Boolean),
  }
}

function isSafePromptCandidate(row: DanbooruCsvRow, minPostCount: number) {
  if (!INCLUDED_DANBOORU_TYPES.has(row.type)) return false
  if (row.postCount < minPostCount) return false
  if (row.name.length > 80) return false
  return !EXCLUDED_NAME_PATTERNS.some((pattern) => pattern.test(row.name))
}

function labelFromDanbooruName(name: string): string {
  return name
    .split('_')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
}

function definitionFromRow(row: DanbooruCsvRow): PromptTagDefinition {
  const isMeta = row.type === '5'
  return {
    id: `danbooru:${isMeta ? 'meta' : 'general'}:${row.name}`,
    type: isMeta ? 'quality' : 'subject',
    source: 'danbooru',
    label: labelFromDanbooruName(row.name),
    promptText: row.name,
    aliases: row.aliases,
    category: isMeta ? 'quality' : 'scene',
    polarity: 'positive',
    modelFamilies: ['sdxl', 'anima', 'novelai'],
    orderGroup: isMeta ? 20 : 40,
    popularity: Math.min(50, Math.floor(row.postCount / 100000)),
  }
}

function renderGeneratedFile(definitions: readonly PromptTagDefinition[]) {
  return `import type { PromptTagDefinition } from '@/types/prompt-tags'

// Generated by scripts/import-danbooru-prompt-tags.ts.
// Source CSV format: <name>,<type>,<postCount>,"<aliases>".
export const PROMPT_TAG_DANBOORU_DEFINITIONS = ${JSON.stringify(
    definitions,
    null,
    2,
  )} satisfies readonly PromptTagDefinition[]
`
}

async function main() {
  const options = parseArgs(process.argv)
  const raw = await readFile(options.inputPath, 'utf8')
  const definitions = raw
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map(parseDanbooruRow)
    .filter((row): row is DanbooruCsvRow => row !== null)
    .filter((row) => isSafePromptCandidate(row, options.minPostCount))
    .map(definitionFromRow)

  await writeFile(options.outputPath, renderGeneratedFile(definitions), 'utf8')
  console.log(
    `Wrote ${definitions.length} Danbooru prompt tags to ${options.outputPath}`,
  )
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error)
  console.error(message)
  process.exit(1)
})
