'use client'

/**
 * Icon barrel — the single import site for icons under `src/`.
 *
 * Phosphor is the icon base (owner, 2026-09-17), and the only one — lucide is
 * uninstalled and importing it anywhere under `src/**` is an eslint error.
 * Global weight/size defaults live in `IconDefaults.tsx`.
 *
 * ⚠ The lucide spellings below are **migration-era aliases**: they existed so
 * moving a file was an import-path change and nothing else. New code writes the
 * Phosphor name (`MagnifyingGlass`, `CaretDown`, `Trash`), not the lucide one
 * (`Search`, `ChevronDown`, `Trash2`). Adding an icon means adding the Phosphor
 * export — ⛔ do not mint a new lucide-shaped alias for it.
 *
 * Semantic duplicates are collapsed on purpose: `Image` / `ImageIcon` share one
 * glyph, and `AlertTriangle` / `TriangleAlert` / `AlertCircle` / `CircleAlert`
 * land on Phosphor `Warning` and `WarningCircle`.
 *
 * The five lucide glyphs with no Phosphor counterpart (`FolderSearch`,
 * `ImageDown`, `ImagePlus`, `MessageCircleWarning`, `MessageSquarePlus`) are
 * resolved by call-site meaning rather than by shape; each carries the reason
 * inline. Nothing here imports from lucide any more.
 */

export type {
  Icon,
  // lucide's component type, kept as an alias so `type LucideIcon`
  // call sites migrate with an import-path change and nothing else.
  Icon as LucideIcon,
  IconProps,
  IconWeight,
} from '@phosphor-icons/react'
export { IconContext } from '@phosphor-icons/react'

export {
  // Spinner glyph — replaces lucide `Loader2`; see `@/components/ui/spinner`.
  CircleNotchIcon as CircleNotch,
  WarningCircleIcon as AlertCircle,
  WarningIcon as AlertTriangle,
  AlignTopIcon as AlignVerticalJustifyStart,
  ArchiveIcon as Archive,
  ArrowsDownUpIcon as ArrowDownUp,
  ArrowLeftIcon as ArrowLeft,
  ArrowsLeftRightIcon as ArrowLeftRight,
  ArrowRightIcon as ArrowRight,
  ArrowsLeftRightIcon as ArrowRightLeft,
  ArrowUpIcon as ArrowUp,
  ArrowsDownUpIcon as ArrowUpDown,
  ArrowUpRightIcon as ArrowUpRight,
  AtIcon as AtSign,
  WaveformIcon as AudioLines,
  ProhibitIcon as Ban,
  SquaresFourIcon as Blocks,
  BookmarkSimpleIcon as BookmarkPlus,
  BookOpenIcon as BookOpen,
  AddressBookIcon as BookUser,
  RobotIcon as Bot,
  CubeIcon as Box,
  CubeFocusIcon as Boxes,
  CameraIcon as Camera,
  CheckIcon as Check,
  ChecksIcon as CheckCheck,
  CheckCircleIcon as CheckCircle2,
  CheckIcon as CheckIcon,
  CaretDownIcon as ChevronDown,
  CaretDownIcon as ChevronDownIcon,
  CaretLeftIcon as ChevronLeft,
  CaretRightIcon as ChevronRight,
  CaretRightIcon as ChevronRightIcon,
  CaretUpIcon as ChevronUp,
  CaretUpIcon as ChevronUpIcon,
  CircleIcon as Circle,
  WarningCircleIcon as CircleAlert,
  CheckCircleIcon as CircleCheck,
  CurrencyCircleDollarIcon as CircleDollarSign,
  QuestionIcon as CircleHelp,
  CircleIcon as CircleIcon,
  ProhibitIcon as CircleSlash,
  XCircleIcon as CircleX,
  FilmSlateIcon as Clapperboard,
  ClipboardIcon as Clipboard,
  ClipboardTextIcon as ClipboardCheck,
  ClockIcon as Clock,
  CloudFogIcon as CloudFog,
  CloudRainIcon as CloudRain,
  CloudSnowIcon as CloudSnow,
  CloudSunIcon as CloudSun,
  CoinsIcon as Coins,
  CompassIcon as Compass,
  CopyIcon as Copy,
  CpuIcon as Cpu,
  CropIcon as Crop,
  DiceFiveIcon as Dice5,
  DiceSixIcon as Dices,
  DownloadSimpleIcon as Download,
  PencilSimpleIcon as Edit3,
  EraserIcon as Eraser,
  ArrowsOutSimpleIcon as Expand,
  ArrowSquareOutIcon as ExternalLink,
  EyeIcon as Eye,
  EyeSlashIcon as EyeOff,
  FastForwardIcon as FastForward,
  FileIcon as File,
  FileAudioIcon as FileAudio2,
  FileArrowDownIcon as FileDown,
  FileTextIcon as FileText,
  FileArrowUpIcon as FileUp,
  FileVideoIcon as FileVideo,
  FilmStripIcon as Film,
  FlagIcon as Flag,
  FolderIcon as Folder,
  FolderOpenIcon as FolderInput,
  FolderOpenIcon as FolderOpen,
  FolderPlusIcon as FolderPlus,
  // lucide `FolderSearch` — no folder+magnifier in Phosphor 2.1.10. The only
  // call site is the `listAssetFolders` tool icon, so the folder *stack* says
  // what the tool returns better than a magnifier would.
  FoldersIcon as FolderSearch,
  TreeStructureIcon as FolderTree,
  FolderMinusIcon as FolderX,
  FrameCornersIcon as Frame,
  StackIcon as GalleryVerticalEnd,
  GaugeIcon as Gauge,
  GiftIcon as Gift,
  GlobeIcon as Globe,
  GlobeHemisphereWestIcon as Globe2,
  GlobeXIcon as GlobeLock,
  SquaresFourIcon as Grid2x2,
  GridNineIcon as Grid3X3,
  DotsSixIcon as GripHorizontal,
  DotsSixVerticalIcon as GripVertical,
  HandIcon as Hand,
  HeartIcon as Heart,
  HeartBreakIcon as HeartOff,
  QuestionIcon as HelpCircle,
  ClockCounterClockwiseIcon as History,
  HouseIcon as Home,
  IdentificationCardIcon as IdCard,
  ImageIcon as Image,
  // lucide `ImageDown` — no image+arrow in Phosphor. Its one call site is the
  // assistant dock's drag-over hint, where the down arrow is the whole message.
  DownloadSimpleIcon as ImageDown,
  ImageIcon as ImageIcon,
  ImageBrokenIcon as ImageOff,
  // lucide `ImagePlus` — no image+plus in Phosphor. Every call site is "attach
  // an image" next to a label or inside an add menu, so the framed-image glyph
  // carries the noun and the surrounding affordance carries the verb. Distinct
  // from `Image` on purpose.
  ImageSquareIcon as ImagePlus,
  ImagesIcon as Images,
  InfoIcon as Info,
  KeyIcon as Key,
  KeyboardIcon as Keyboard,
  KeyIcon as KeyRound,
  TranslateIcon as Languages,
  StackSimpleIcon as Layers,
  SquaresFourIcon as LayoutGrid,
  BooksIcon as Library,
  LinkIcon as Link2,
  LinkBreakIcon as Link2Off,
  ListChecksIcon as ListChecks,
  ListNumbersIcon as ListOrdered,
  TreeStructureIcon as ListTree,
  CrosshairIcon as Locate,
  LockIcon as Lock,
  LockKeyIcon as LockKeyhole,
  SignOutIcon as LogOut,
  MapTrifoldIcon as Map,
  ArrowsOutIcon as Maximize2,
  // lucide `MessageCircleWarning` — its one call site is the "pronunciation
  // error" audio-feedback chip, sitting in a row of plain descriptive glyphs.
  // A speech bubble with text reads as speech; `WarningCircle` would have
  // turned one chip in that row into an alert.
  ChatCircleTextIcon as MessageCircleWarning,
  // lucide `MessageSquarePlus` — no chat+plus in Phosphor. All three call sites
  // are "new conversation" controls carrying their own label/aria-label, and
  // compose is the glyph that means "start a new one".
  NotePencilIcon as MessageSquarePlus,
  ChatsCircleIcon as MessagesSquare,
  MicrophoneIcon as Mic,
  MicrophoneStageIcon as Mic2,
  ArrowsInIcon as Minimize2,
  MinusIcon as Minus,
  MinusCircleIcon as MinusCircle,
  MoonIcon as Moon,
  DotsThreeIcon as MoreHorizontal,
  MountainsIcon as Mountain,
  CursorIcon as MousePointer2,
  ArrowsHorizontalIcon as MoveHorizontal,
  MusicNoteIcon as Music,
  MusicNoteIcon as Music2,
  NotePencilIcon as NotebookPen,
  PaintBrushIcon as Paintbrush,
  PaletteIcon as Palette,
  SidebarIcon as PanelLeft,
  SidebarSimpleIcon as PanelLeftClose,
  SidebarIcon as PanelLeftIcon,
  SidebarIcon as PanelLeftOpen,
  SidebarSimpleIcon as PanelRightClose,
  LayoutIcon as PanelsTopLeft,
  PaperclipIcon as Paperclip,
  PauseIcon as Pause,
  PencilIcon as Pencil,
  PencilSimpleLineIcon as PencilLine,
  PencilSimpleLineIcon as PenLine,
  PenNibIcon as PenTool,
  PictureInPictureIcon as PictureInPicture2,
  PushPinIcon as Pin,
  PlayIcon as Play,
  PlusIcon as Plus,
  RectangleIcon as RatioIcon,
  RectangleIcon as RectangleHorizontal,
  ArrowUUpRightIcon as Redo2,
  ArrowsCounterClockwiseIcon as RefreshCcw,
  ArrowsClockwiseIcon as RefreshCw,
  SwapIcon as Replace,
  RewindIcon as Rewind,
  ArrowCounterClockwiseIcon as RotateCcw,
  ArrowClockwiseIcon as RotateCw,
  FloppyDiskIcon as Save,
  ScanIcon as ScanEye,
  ScanIcon as ScanText,
  ScissorsIcon as Scissors,
  ScrollIcon as ScrollText,
  MagnifyingGlassIcon as Search,
  PaperPlaneTiltIcon as Send,
  PaperPlaneRightIcon as SendHorizontal,
  GearIcon as Settings,
  GearSixIcon as Settings2,
  ShapesIcon as Shapes,
  ShareNetworkIcon as Share2,
  ShieldIcon as Shield,
  ShieldWarningIcon as ShieldAlert,
  ShieldCheckIcon as ShieldCheck,
  ShuffleIcon as Shuffle,
  SkipForwardIcon as SkipForward,
  SlidersHorizontalIcon as SlidersHorizontal,
  SmileyIcon as Smile,
  SmileyStickerIcon as SmilePlus,
  SparkleIcon as Sparkles,
  SquareIcon as Square,
  SelectionIcon as SquareDashed,
  NotePencilIcon as SquarePen,
  StarIcon as Star,
  SkipForwardIcon as StepForward,
  NoteIcon as StickyNote,
  SunIcon as Sun,
  SunHorizonIcon as Sunrise,
  SunHorizonIcon as Sunset,
  SwatchesIcon as SwatchBook,
  TagIcon as Tag,
  TagIcon as Tags,
  ListMagnifyingGlassIcon as TextSearch,
  ThumbsUpIcon as ThumbsUp,
  TrashIcon as Trash2,
  TreeIcon as Trees,
  WarningIcon as TriangleAlert,
  TextTIcon as Type,
  ArrowUUpLeftIcon as Undo2,
  PlugsIcon as Unplug,
  UploadSimpleIcon as Upload,
  CloudArrowUpIcon as UploadCloud,
  UserIcon as User,
  UserCheckIcon as UserCheck,
  UserCircleIcon as UserCircle,
  UserPlusIcon as UserPlus,
  UserIcon as UserRound,
  UsersIcon as Users,
  VideoCameraIcon as Video,
  // Phosphor spellings (⛔ 不新造 lucide 形状的别名，见文件头)：画布视频卡提示词栏
  // 那颗声音开关用的就是这一对。
  SpeakerHighIcon as SpeakerHigh,
  SpeakerSlashIcon as SpeakerSlash,
  SpeakerHighIcon as Volume2,
  SpeakerXIcon as VolumeX,
  MagicWandIcon as Wand2,
  MagicWandIcon as WandSparkles,
  GraphIcon as Waypoints,
  WindIcon as Wind,
  XIcon as X,
  XCircleIcon as XCircle,
  XIcon as XIcon,
  LightningIcon as Zap,
  LightningSlashIcon as ZapOff,
  MagnifyingGlassPlusIcon as ZoomIn,
  MagnifyingGlassMinusIcon as ZoomOut,
} from '@phosphor-icons/react'

// TODO phosphor — lucide `Loader2` is deliberately NOT re-exported. Spinners go
// through `@/components/ui/spinner`, which renders `CircleNotch`.
